Made changes for AM62A_QNX for single cam and tidl demo
TexasInstruments/edgeai-tiovx-apps pull request #91
Opened 2024-10-22 12:35 UTC by Akshay-Abdar

Made necessary changes to support single camera application and TIDL based classification demo on AM62A_QNX.

2024-10-29 13:04 UTC, ravi-rahul requested changes

2024-10-29 13:04 UTC, ravi-rahul commented on modules/src/QNX_display_module.c
> +    err = screen_create_context(&screen_ctx, SCREEN_APPLICATION_CONTEXT);
is this needed for every frame
Can this be done in a init function?

2024-10-29 13:04 UTC, ravi-rahul commented on modules/src/QNX_display_module.c
> +
I guess all the above calls are required to be done only once per run, not for every frame
Please check and create a init function to call these things

2024-10-29 13:04 UTC, ravi-rahul commented on modules/src/QNX_display_module.c
> +        int buffer_size[2];
indentation?

2024-10-29 13:04 UTC, ravi-rahul commented on modules/src/tiovx_aewb_module.c
> +    //node_priv->params.awb_mode = node_cfg->awb_mode;
why commented?

2024-10-29 13:04 UTC, ravi-rahul commented on modules/src/tiovx_capture_module.c
> +
?

2024-10-29 13:04 UTC, ravi-rahul commented on modules/src/tiovx_sensor_module.c
> +        //status = VX_FAILURE; // commented forcefully
?

2024-11-25 13:10 UTC, shiva-ti commented on cmake/common.cmake
> +                 ${QNX_LIB_PATH}
can this break linux builds ? psdkqa exists only for QNX SDK

2024-11-25 13:11 UTC, shiva-ti commented on modules/core/src/tiovx_modules_cbs.c
> +    },
Please remove all trailing spaces, new line differences

2024-11-25 13:12 UTC, shiva-ti commented on modules/include/qnx_display_module.h
> +#ifndef _qnx_DISPLAY_MODULE
is this newly added macro ? try to use CAPS for macro

2024-11-25 13:14 UTC, shiva-ti commented on tests/app_tiovx_capture_dl_display_pipeline.c
> +
can we use else condition here ?

2024-11-25 13:15 UTC, shiva-ti commented on tests/app_tiovx_capture_dl_display_pipeline.c
> +#define POST_PROC_OUT_WIDTH   (1920)
do we need QNX -AM62A flag here, to avoid breaking previous code ?

2024-11-25 13:19 UTC, shiva-ti commented on tests/app_tiovx_capture_dl_display_pipeline.c
> +    #if !defined(SOC_AM62A)
QNX flag is also oneeded

2024-11-29 08:56 UTC, shiva-ti commented on cmake/common.cmake
> +         ti-csirxlld
csirx, fvid2 libraries are QNX specific for AM62A only, for Jacinto these are on R5. Please add AM62A check here

2024-11-29 08:57 UTC, shiva-ti commented on modules/core/include/tiovx_modules_cbs.h
> +#if !defined(SOC_AM62A)
are these exluded header files needed for AM62A-Linux ? if yes, please add QNX flag as well

2024-11-29 08:59 UTC, shiva-ti commented on modules/src/qnx_display_module.c
> +    static uint32_t j=0;
can you rename i,j varibales to something more relevant ? so that the variable names reflect their usage here

2024-11-29 09:01 UTC, shiva-ti commented on tests/CMakeLists.txt
> +if ("${TARGET_CPU}" STREQUAL "A72" OR "${TARGET_CPU}" STREQUAL "A53")
will this affect Jacinto ? why are we adding A72 core here ?

2024-12-03 09:13 UTC, ravi-rahul requested changes

2024-12-03 09:13 UTC, ravi-rahul commented on apps/src/input_block.c
> +           v4l2_pix_format = v4l2_fourcc('B','G','I','0');
wrong indentation

2024-12-03 09:13 UTC, ravi-rahul commented on modules/CMakeLists.txt
> +         src/omx_decode_module.c
This should be protected for AM62A

2024-12-03 09:13 UTC, ravi-rahul commented on modules/include/qnx_display_module.h
> +
Remove this empty lines

2025-03-03 06:01 UTC, ravi-rahul approved these changes

2025-03-03 06:02 UTC, ravi-rahul approved these changes

2025-03-03 06:02 UTC, merged